const PDFDocument = require("pdfkit");

function sanitizeText(text) {
  return (text || "").replace(/\r\n/g, "\n").replace(/\t/g, "    ").trim();
}
function splitIntoLines(text) { return sanitizeText(text).split("\n"); }
function isHeading(line) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.length > 120) return false;
  if (/^[A-Z0-9 .:/()\-]+$/.test(trimmed) && trimmed.length > 5) return true;
  if (/^(section|chapter|part|appendix|warning|caution|note)\b/i.test(trimmed)) return true;
  return false;
}
function isBullet(line) { return /^\s*(-|•|\*|\d+\.|[a-zA-Z]\))\s+/.test(line); }
function cleanBullet(line) { return line.replace(/^\s*(-|•|\*|\d+\.|[a-zA-Z]\))\s+/, "").trim(); }
function addFooter(doc, pageNumber) {
  const bottom = doc.page.height - 45;
  doc.fontSize(8).fillColor("#64748b").text(`Generated by TranslateManual.ai - Page ${pageNumber}`, 50, bottom, { align: "center", width: doc.page.width - 100 });
  doc.fillColor("#0f172a");
}
function createTranslatedPdfBuffer({ title, sourceLanguage, targetLanguage, translatedText }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margins: { top: 60, bottom: 70, left: 55, right: 55 },
        bufferPages: true,
        info: { Title: title || "Translated Manual", Author: "TranslateManual.ai", Subject: "AI translated technical manual" },
      });
      const chunks = [];
      doc.on("data", chunk => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.font("Helvetica-Bold").fontSize(20).fillColor("#0f172a").text(title || "Translated Manual", { align: "center" });
      doc.moveDown(0.5);
      doc.font("Helvetica").fontSize(9).fillColor("#475569").text(`Source: ${sourceLanguage || "auto"}  |  Target: ${targetLanguage}`, { align: "center" });
      doc.moveDown(1.5);
      doc.fillColor("#0f172a");
      for (const rawLine of splitIntoLines(translatedText)) {
        const line = rawLine.trim();
        if (!line) { doc.moveDown(0.5); continue; }
        if (/^---PAGE BREAK---$/i.test(line)) { doc.addPage(); continue; }
        if (isHeading(line)) {
          doc.moveDown(0.5);
          doc.font("Helvetica-Bold").fontSize(13).fillColor("#111827").text(line, { paragraphGap: 6 });
          doc.moveDown(0.25);
          continue;
        }
        if (isBullet(line)) {
          doc.font("Helvetica").fontSize(10).fillColor("#0f172a").text(`• ${cleanBullet(line)}`, { indent: 18, paragraphGap: 4, lineGap: 2, align: "left" });
          continue;
        }
        doc.font("Helvetica").fontSize(10).fillColor("#0f172a").text(line, { paragraphGap: 4, lineGap: 2, align: "left" });
      }
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) { doc.switchToPage(i); addFooter(doc, i + 1); }
      doc.end();
    } catch (error) { reject(error); }
  });
}
module.exports = { createTranslatedPdfBuffer };
